---
deployment:
  tasks:
    - export DEPLOYPATH=/home/huizehigh5/public_html
    - /bin/cp -R Commissies $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp addquote.php $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp fotos.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp quotes.html $DEPLOYPATH 